package com.example.demo.entities;

public enum IngredientCondition {
    FRESH, UNRIPE, RIPE, OVERRIPE, STARTING_TO_SPOIL, ROTTEN,
    FROZEN, CANNED_OR_PRESERVED, DRIED, PICKLED, SMOKED, BLANCHED_OR_BOILED, COOKED, ROASTED_OR_GRILLED, FRIED, FERMENTED;
}
